import { inject, Injectable } from '@angular/core';
import { doc, Firestore, setDoc } from '@angular/fire/firestore';
import { BlogPostHelper } from '../../../core/helpers/blog-post.helper';

@Injectable({
  providedIn: 'root',
})
export class BlogPostService {
  firestore = inject(Firestore);

  createPost(title: string, content: string) {
    if (title === '' && content === '') return;

    const postsCollectionRef = doc(this.firestore, 'posts', BlogPostHelper.createSlug(title));
    //addDoc: genera la colección con id autogenerated para documento
    //setDoc: genera la colección con id generado por nosotros para documento
    setDoc(postsCollectionRef, {
      title: title,
      content: content,
      publishedOn: new Date(),
    });
  }
}
